### ISSUE TITLE
NPC Not there

### ISSUE THREAD

**Issue by UptownFunk** [LukeWasTakenn/luke_vehiclegarage#13]
Hello.

I have installed everything (Renamed to luke_vehiclegarage, Installed PolyZone, qtarget, nh-context)

But  The NPC Wont Show up.

When I press ALT The Eye pops up, thats all.

Im using: ESX_Legacy

FiveM Server Version: 4394 ("version" is "FXServer-master v1.0.0.4394 linux")

**Comment by UptownFunk** [comment]
Tried putting `set sv_enforceGameBuild 2189` in my cfg, didn't fix anything

**Comment by LukeWasTakenn** [comment]
Is this happening on a garage that you added or one of the base ones included?

**Comment by UptownFunk** [comment]
I haven't touched any files. It's a garage that was already added.

**Comment by LukeWasTakenn** [comment]
No console errors?

**Comment by UptownFunk** [comment]
Nope, none.

Only this on the client console: 
![image](https://user-images.githubusercontent.com/91493227/134963181-873d9dd1-d96f-4dc2-afa7-dc722fa50cce.png)

But that is because the script can't find the npc so it can't display the blip.

**Comment by LukeWasTakenn** [comment]
No it's not. That function creates the blip based on the same coords as the peds are located at.

Try and take that whole function from the client.lua file (it's located somewhere at the very bottom) and put it at the very top and let me know what happens.

**Comment by UptownFunk** [comment]
NPC Seems to appear now! (+ Blip)

But when I press the Alt Button now, nothing happens. (The eye won't pop up anymore either)

**Comment by LukeWasTakenn** [comment]
Like the eye won't pop up at all or the interaction with the ped on the eye doesn't pop up?

**Comment by UptownFunk** [comment]
Both

**Comment by LukeWasTakenn** [comment]
Changing the location of a function wouldn't suddenly break a different resource lol

**Comment by UptownFunk** [comment]
Idk what you mean, but before when  i pressed alt the eye logo appeared now it doesn't.

(the ped is there) but the menu doesn't appear

**Comment by LukeWasTakenn** [comment]
And your eye doesn't show up when you hold ALT at all?

**Comment by UptownFunk** [comment]
Yes, when I hold ALT the eye does not appear

**Comment by LukeWasTakenn** [comment]
I have pushed a fix for this but I was not able to replicate the issue where the eye disappears, meaning it's likely some issue on your side.
