### ISSUE TITLE
Started

### ISSUE THREAD

**Issue by Mateusz57698** [LukeWasTakenn/luke_vehiclegarage#14]
[script:luke_vehicleg] Error loading script server/server.lua in resource luke_vehiclegarage: @luke_vehiclegarage/server/server.lua:1: attempt to index a nil value (global 'ESX')
[script:luke_vehicleg] stack traceback:
[script:luke_vehicleg]  @luke_vehiclegarage/server/server.lua:1: in main chunk

**Comment by LukeWasTakenn** [comment]
> This resource now only supports ESX Legacy, other versions of the framework will not work without modifying the resource.

**Comment by Mateusz57698** [comment]
i used extendedmode
