### ISSUE TITLE
Owned car won't show after i relog or after a server restart

### ISSUE THREAD

**Issue by RavenHart1** [LukeWasTakenn/luke_vehiclegarage#2]
Hi ! 
I'm currently using v1.finale version of ESX and wished to use your garage script. I previously installed it on an older version of ESX and it was working perfectly. Although, now when i buy a car i can put it in the garage and then take it out but as soon as i relog into the server or do a server reboot no cars shows in the garage but they are present in the DB. 

No errors anywhere so i'm kinda lost as to why it won't fetch the information. Please help?

**Comment by LukeWasTakenn** [comment]
It sounds to me like maybe your identifier in the table is longer than it's limit so it can't get the data. Try increasing the owner column to 50 varchar limit and let me know what happens.

**Comment by RavenHart1** [comment]
> It sounds to me like maybe your identifier in the table is longer than it's limit so it can't get the data. Try increasing the owner column to 50 varchar limit and let me know what happens.

Yeeep ! that fixed it! sorry that was a silly mistake :)  Btw i absolutely love this ressource. Its a fresh breath of air and adds a touch of realism to have the car spawn out in different parkings instead of in one random spot :)

**Comment by LukeWasTakenn** [comment]
Thanks! Also that's my mistake not yours because I originally developed this on ESX 1.1, which uses steam identifiers which are shorter. ESX V1 Final uses Rockstar license identifiers which are longer and can vary in length. So I forgot to change the limit in the table. Sorry.
