### ISSUE TITLE
[Feat] request for impounding feature changes and garage type changes

### ISSUE THREAD

**Issue by MrNewb** [LukeWasTakenn/luke_vehiclegarage#20]
Requesting for a feature to be implemented to the impound to run off os time to remove a owned vehicle from owned vehicle tables until the time has passed. an example for this can be seen in this https://github.com/XxFri3ndlyxX/esx_impound. Aside from that config options to have vehicles restored on restart would be good.

Additionally requesting a job garage system be implemented, job vehicles stored separately than standard cars and be restricted to only been pulled out from the job garage with a marker only visible to people assigned at the job. Something that could replace the need for ambulancejob/policejob vehicle garage system.

Just wanted to throw out some ideas for ya.

**Comment by LukeWasTakenn** [comment]
Currently I'm working on having a config option to split garages, job garages can come some time later in the future.

I will consider a config option to restore all vehicles on restart.

**Comment by MrNewb** [comment]
<3 you luke

**Comment by LukeWasTakenn** [comment]
I added a config option to restore vehicles on resource start, job garages will probably come some time later in the future.
