### ISSUE TITLE
i got this error

### ISSUE THREAD

**Issue by colector-user** [LukeWasTakenn/luke_vehiclegarage#3]
https://cdn.discordapp.com/attachments/709024730392297582/873562741506469948/eda16c45f0cf8ffb.png

**Comment by LukeWasTakenn** [comment]
Are you starting qtarget before the garages?

**Comment by colector-user** [comment]
yes

**Comment by colector-user** [comment]
same error when started after

**Comment by LukeWasTakenn** [comment]
What version of qtarget are you using?

**Comment by colector-user** [comment]
last version from post

**Comment by LukeWasTakenn** [comment]
I haven't tested it with the latest release yet, and you are running ESX Legacy, right?

**Comment by colector-user** [comment]
Nope, im useing extendedmode

**Comment by colector-user** [comment]
I was using your old version of the garage and it was working fine, when I saw an update I liked it and switched it and got this error

**Comment by LukeWasTakenn** [comment]
Because the new version is rewritten to fully support ESX Legacy with qtarget support intended with ESX Legacy not standalone. You'll most likely have to do some converting to get it to work

**Comment by colector-user** [comment]
I wish I could use it, but I'm not good at Scripting.Thank you for answer. Good luck!
