### ISSUE TITLE
damage doesn't save for me 

### ISSUE THREAD

**Issue by wtftanveer** [LukeWasTakenn/luke_vehiclegarage#5]
vehicle damage doesn't save for me I import SQL and everything .

**Comment by LukeWasTakenn** [comment]
Any errors? What are the health values in the database after you stored the car in the garage after throwing it around?

**Comment by wtftanveer** [comment]
Oh, It's working now sorry for bothering you .

**Comment by wtftanveer** [comment]
but I have a suggestion , when I store a vehicle in a garage it won't change state instead in the garage menu it will show which garage I store the vehicle.
