### ISSUE TITLE
car names 

### ISSUE THREAD

**Issue by strongprincess** [LukeWasTakenn/luke_vehiclegarage#7]
car names still null 
![20210921203903_1](https://user-images.githubusercontent.com/81395433/134266527-ee191ef7-44bd-4b90-a852-426809a5be94.jpg)
vehicle_names.lau is 
Citizen.CreateThread(function()
     AddTextEntry('bc205500w', 'towtruck')
     AddTextEntry('20 RAM 5500 Wrecker', '20 RAM 5500 Wrecker')

     AddTextEntry('killerrig' 'Truck')
     AddTextEntry('Killer Rig' 'killerrig')
    -- Example: 
    -- AddTextEntry('gtr', "Skyline GTR '17") -- For the car name itself
    -- AddTextEntry('Nissan', 'Nissan') -- For the make name (in vehicles.meta -> <vehicleMakeName>)
end)

**Comment by LukeWasTakenn** [comment]
You clearly edited the resource to use ESX's menu instead of nh-context. Like how do you even expect me to help you when I don't even know how and what all you've changed.
